<?php

namespace Database\Seeders;

use App\Models\AssistanceProgram;
use App\Models\AssistanceRecipient;
use App\Models\GuestLog;
use App\Models\Household;
use App\Models\HouseholdMovement;
use App\Models\Resident;
use App\Models\Rt;
use App\Models\RtOfficial;
use App\Models\User;
use App\Models\Vehicle;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class ResetDemoDataSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        // Clear dependent data first.
        AssistanceRecipient::truncate();
        AssistanceProgram::truncate();
        GuestLog::truncate();
        HouseholdMovement::truncate();
        Vehicle::truncate();
        RtOfficial::truncate();
        Resident::truncate();
        Household::truncate();
        Rt::truncate();

        // Remove non-admin users to avoid stale references.
        User::query()
            ->where('email', '!=', 'admin@warga.test')
            ->delete();

        User::query()
            ->where('email', 'admin@warga.test')
            ->update([
                'is_active' => true,
                'is_admin' => true,
                'role' => 'admin',
                'rt_id' => null,
            ]);

        Schema::enableForeignKeyConstraints();

        $today = Carbon::today();

        $rtDefinitions = [
            [
                'number' => '01',
                'name' => 'RT 01 - Melati',
                'email' => 'rt01@warga.test',
                'leader_email' => 'budi.santoso@rt01.warga.test',
                'leader_started_at' => $today->copy()->subYears(2)->startOfYear(),
                'households' => [
                    [
                        'family_card_number' => '317401010001',
                        'address' => 'Jl. Melati No. 1',
                        'issued_at' => $today->copy()->subYears(8),
                        'head' => [
                            'name' => 'Budi Santoso',
                            'nik' => '3174010101010001',
                            'gender' => 'male',
                            'birth_place' => 'Jakarta',
                            'birth_date' => '1978-05-12',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Wiraswasta',
                            'marital_status' => 'Kawin',
                            'email' => 'budi.santoso@rt01.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Budi Santoso',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1978-05-12',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Wiraswasta',
                                'marital_status' => 'Kawin',
                                'email' => 'budi.santoso@rt01.warga.test',
                            ],
                            [
                                'name' => 'Siti Rahmawati',
                                'relationship' => 'Istri',
                                'gender' => 'female',
                                'birth_place' => 'Bandung',
                                'birth_date' => '1980-09-03',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Ibu Rumah Tangga',
                                'marital_status' => 'Kawin',
                                'email' => 'siti.rahmawati@rt01.warga.test',
                            ],
                            [
                                'name' => 'Andi Santoso',
                                'relationship' => 'Anak',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '2008-02-18',
                                'religion' => 'Islam',
                                'education' => 'SMP',
                                'occupation' => 'Pelajar',
                                'marital_status' => 'Belum Kawin',
                                'email' => 'andi.santoso@rt01.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401010002',
                        'address' => 'Jl. Melati No. 5',
                        'issued_at' => $today->copy()->subYears(5),
                        'head' => [
                            'name' => 'Dewi Lestari',
                            'nik' => '3174010102020002',
                            'gender' => 'female',
                            'birth_place' => 'Bogor',
                            'birth_date' => '1985-01-22',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Guru',
                            'marital_status' => 'Kawin',
                            'email' => 'dewi.lestari@rt01.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Dewi Lestari',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'female',
                                'birth_place' => 'Bogor',
                                'birth_date' => '1985-01-22',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Guru',
                                'marital_status' => 'Kawin',
                                'email' => 'dewi.lestari@rt01.warga.test',
                            ],
                            [
                                'name' => 'Rahmat Prakoso',
                                'relationship' => 'Suami',
                                'gender' => 'male',
                                'birth_place' => 'Cianjur',
                                'birth_date' => '1982-07-11',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Pegawai Negeri',
                                'marital_status' => 'Kawin',
                                'email' => 'rahmat.prakoso@rt01.warga.test',
                            ],
                            [
                                'name' => 'Nadia Prakoso',
                                'relationship' => 'Anak',
                                'gender' => 'female',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '2012-04-09',
                                'religion' => 'Islam',
                                'education' => 'SD',
                                'occupation' => 'Pelajar',
                                'marital_status' => 'Belum Kawin',
                                'email' => 'nadia.prakoso@rt01.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401010003',
                        'address' => 'Jl. Melati No. 9',
                        'issued_at' => $today->copy()->subYears(6),
                        'head' => [
                            'name' => 'Hendra Wijaya',
                            'nik' => '3174010103030003',
                            'gender' => 'male',
                            'birth_place' => 'Semarang',
                            'birth_date' => '1983-11-30',
                            'religion' => 'Kristen',
                            'education' => 'S1',
                            'occupation' => 'Akuntan',
                            'marital_status' => 'Kawin',
                            'email' => 'hendra.wijaya@rt01.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Hendra Wijaya',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'male',
                                'birth_place' => 'Semarang',
                                'birth_date' => '1983-11-30',
                                'religion' => 'Kristen',
                                'education' => 'S1',
                                'occupation' => 'Akuntan',
                                'marital_status' => 'Kawin',
                                'email' => 'hendra.wijaya@rt01.warga.test',
                            ],
                            [
                                'name' => 'Maria Widya',
                                'relationship' => 'Istri',
                                'gender' => 'female',
                                'birth_place' => 'Semarang',
                                'birth_date' => '1984-06-15',
                                'religion' => 'Kristen',
                                'education' => 'S1',
                                'occupation' => 'Perawat',
                                'marital_status' => 'Kawin',
                                'email' => 'maria.widya@rt01.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401010004',
                        'address' => 'Jl. Melati No. 12',
                        'issued_at' => $today->copy()->subYears(4),
                        'head' => [
                            'name' => 'Lina Kartika',
                            'nik' => '3174010104040004',
                            'gender' => 'female',
                            'birth_place' => 'Jakarta',
                            'birth_date' => '1990-03-05',
                            'religion' => 'Islam',
                            'education' => 'D3',
                            'occupation' => 'Desainer',
                            'marital_status' => 'Kawin',
                            'email' => 'lina.kartika@rt01.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Lina Kartika',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'female',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1990-03-05',
                                'religion' => 'Islam',
                                'education' => 'D3',
                                'occupation' => 'Desainer',
                                'marital_status' => 'Kawin',
                                'email' => 'lina.kartika@rt01.warga.test',
                            ],
                            [
                                'name' => 'Arman Saputra',
                                'relationship' => 'Suami',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1988-08-21',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Karyawan Swasta',
                                'marital_status' => 'Kawin',
                                'email' => 'arman.saputra@rt01.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401010005',
                        'address' => 'Jl. Melati No. 16',
                        'issued_at' => $today->copy()->subYears(3),
                        'head' => [
                            'name' => 'Agus Pratama',
                            'nik' => '3174010105050005',
                            'gender' => 'male',
                            'birth_place' => 'Jakarta',
                            'birth_date' => '1992-12-19',
                            'religion' => 'Islam',
                            'education' => 'SMA',
                            'occupation' => 'Teknisi',
                            'marital_status' => 'Kawin',
                            'email' => 'agus.pratama@rt01.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Agus Pratama',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1992-12-19',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Teknisi',
                                'marital_status' => 'Kawin',
                                'email' => 'agus.pratama@rt01.warga.test',
                            ],
                            [
                                'name' => 'Rina Pratama',
                                'relationship' => 'Istri',
                                'gender' => 'female',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1994-07-08',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Wirausaha',
                                'marital_status' => 'Kawin',
                                'email' => 'rina.pratama@rt01.warga.test',
                            ],
                            [
                                'name' => 'Farhan Pratama',
                                'relationship' => 'Anak',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '2019-11-02',
                                'religion' => 'Islam',
                                'education' => 'PAUD',
                                'occupation' => 'Pelajar',
                                'marital_status' => 'Belum Kawin',
                                'email' => 'farhan.pratama@rt01.warga.test',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'number' => '02',
                'name' => 'RT 02 - Kenanga',
                'email' => 'rt02@warga.test',
                'leader_email' => 'samsul.hidayat@rt02.warga.test',
                'leader_started_at' => $today->copy()->subYears(1)->startOfYear(),
                'households' => [
                    [
                        'family_card_number' => '317401020001',
                        'address' => 'Jl. Kenanga No. 2',
                        'issued_at' => $today->copy()->subYears(7),
                        'head' => [
                            'name' => 'Samsul Hidayat',
                            'nik' => '3174010201010001',
                            'gender' => 'male',
                            'birth_place' => 'Surabaya',
                            'birth_date' => '1975-10-10',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Kontraktor',
                            'marital_status' => 'Kawin',
                            'email' => 'samsul.hidayat@rt02.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Samsul Hidayat',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'male',
                                'birth_place' => 'Surabaya',
                                'birth_date' => '1975-10-10',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Kontraktor',
                                'marital_status' => 'Kawin',
                                'email' => 'samsul.hidayat@rt02.warga.test',
                            ],
                            [
                                'name' => 'Nur Aisyah',
                                'relationship' => 'Istri',
                                'gender' => 'female',
                                'birth_place' => 'Surabaya',
                                'birth_date' => '1978-04-12',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Ibu Rumah Tangga',
                                'marital_status' => 'Kawin',
                                'email' => 'nur.aisyah@rt02.warga.test',
                            ],
                            [
                                'name' => 'Rizky Hidayat',
                                'relationship' => 'Anak',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '2003-06-17',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Pelajar',
                                'marital_status' => 'Belum Kawin',
                                'email' => 'rizky.hidayat@rt02.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401020002',
                        'address' => 'Jl. Kenanga No. 4',
                        'issued_at' => $today->copy()->subYears(6),
                        'head' => [
                            'name' => 'Yuli Andriana',
                            'nik' => '3174010202020002',
                            'gender' => 'female',
                            'birth_place' => 'Tasikmalaya',
                            'birth_date' => '1986-03-28',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Apoteker',
                            'marital_status' => 'Kawin',
                            'email' => 'yuli.andriana@rt02.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Yuli Andriana',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'female',
                                'birth_place' => 'Tasikmalaya',
                                'birth_date' => '1986-03-28',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Apoteker',
                                'marital_status' => 'Kawin',
                                'email' => 'yuli.andriana@rt02.warga.test',
                            ],
                            [
                                'name' => 'Deni Pratomo',
                                'relationship' => 'Suami',
                                'gender' => 'male',
                                'birth_place' => 'Tasikmalaya',
                                'birth_date' => '1984-05-07',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Wiraswasta',
                                'marital_status' => 'Kawin',
                                'email' => 'deni.pratomo@rt02.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401020003',
                        'address' => 'Jl. Kenanga No. 7',
                        'issued_at' => $today->copy()->subYears(5),
                        'head' => [
                            'name' => 'Made Wirawan',
                            'nik' => '3174010203030003',
                            'gender' => 'male',
                            'birth_place' => 'Denpasar',
                            'birth_date' => '1981-01-19',
                            'religion' => 'Hindu',
                            'education' => 'S1',
                            'occupation' => 'Arsitek',
                            'marital_status' => 'Kawin',
                            'email' => 'made.wirawan@rt02.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Made Wirawan',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'male',
                                'birth_place' => 'Denpasar',
                                'birth_date' => '1981-01-19',
                                'religion' => 'Hindu',
                                'education' => 'S1',
                                'occupation' => 'Arsitek',
                                'marital_status' => 'Kawin',
                                'email' => 'made.wirawan@rt02.warga.test',
                            ],
                            [
                                'name' => 'Komang Ayu',
                                'relationship' => 'Istri',
                                'gender' => 'female',
                                'birth_place' => 'Denpasar',
                                'birth_date' => '1983-09-01',
                                'religion' => 'Hindu',
                                'education' => 'SMA',
                                'occupation' => 'Pengajar',
                                'marital_status' => 'Kawin',
                                'email' => 'komang.ayu@rt02.warga.test',
                            ],
                            [
                                'name' => 'Kadek Bima',
                                'relationship' => 'Anak',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '2010-10-23',
                                'religion' => 'Hindu',
                                'education' => 'SMP',
                                'occupation' => 'Pelajar',
                                'marital_status' => 'Belum Kawin',
                                'email' => 'kadek.bima@rt02.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401020004',
                        'address' => 'Jl. Kenanga No. 10',
                        'issued_at' => $today->copy()->subYears(4),
                        'head' => [
                            'name' => 'Ratna Sari',
                            'nik' => '3174010204040004',
                            'gender' => 'female',
                            'birth_place' => 'Jakarta',
                            'birth_date' => '1991-12-02',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Analis Data',
                            'marital_status' => 'Kawin',
                            'email' => 'ratna.sari@rt02.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Ratna Sari',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'female',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1991-12-02',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Analis Data',
                                'marital_status' => 'Kawin',
                                'email' => 'ratna.sari@rt02.warga.test',
                            ],
                            [
                                'name' => 'Adi Nugroho',
                                'relationship' => 'Suami',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1989-04-18',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Programmer',
                                'marital_status' => 'Kawin',
                                'email' => 'adi.nugroho@rt02.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401020005',
                        'address' => 'Jl. Kenanga No. 14',
                        'issued_at' => $today->copy()->subYears(3),
                        'head' => [
                            'name' => 'Rafi Pradana',
                            'nik' => '3174010205050005',
                            'gender' => 'male',
                            'birth_place' => 'Jakarta',
                            'birth_date' => '1993-08-14',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Marketing',
                            'marital_status' => 'Kawin',
                            'email' => 'rafi.pradana@rt02.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Rafi Pradana',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1993-08-14',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Marketing',
                                'marital_status' => 'Kawin',
                                'email' => 'rafi.pradana@rt02.warga.test',
                            ],
                            [
                                'name' => 'Sarah Pradana',
                                'relationship' => 'Istri',
                                'gender' => 'female',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '1995-02-20',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Wiraswasta',
                                'marital_status' => 'Kawin',
                                'email' => 'sarah.pradana@rt02.warga.test',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'number' => '03',
                'name' => 'RT 03 - Anggrek',
                'email' => 'rt03@warga.test',
                'leader_email' => 'yosef.manjuntak@rt03.warga.test',
                'leader_started_at' => $today->copy()->subYears(3)->startOfYear(),
                'households' => [
                    [
                        'family_card_number' => '317401030001',
                        'address' => 'Jl. Anggrek No. 3',
                        'issued_at' => $today->copy()->subYears(9),
                        'head' => [
                            'name' => 'Yosef Manjuntak',
                            'nik' => '3174010301010001',
                            'gender' => 'male',
                            'birth_place' => 'Medan',
                            'birth_date' => '1972-02-08',
                            'religion' => 'Katolik',
                            'education' => 'S2',
                            'occupation' => 'Dosen',
                            'marital_status' => 'Kawin',
                            'email' => 'yosef.manjuntak@rt03.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Yosef Manjuntak',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'male',
                                'birth_place' => 'Medan',
                                'birth_date' => '1972-02-08',
                                'religion' => 'Katolik',
                                'education' => 'S2',
                                'occupation' => 'Dosen',
                                'marital_status' => 'Kawin',
                                'email' => 'yosef.manjuntak@rt03.warga.test',
                            ],
                            [
                                'name' => 'Clara Marbun',
                                'relationship' => 'Istri',
                                'gender' => 'female',
                                'birth_place' => 'Medan',
                                'birth_date' => '1975-05-30',
                                'religion' => 'Katolik',
                                'education' => 'S1',
                                'occupation' => 'Dokter',
                                'marital_status' => 'Kawin',
                                'email' => 'clara.marbun@rt03.warga.test',
                            ],
                            [
                                'name' => 'Davin Manjuntak',
                                'relationship' => 'Anak',
                                'gender' => 'male',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '2004-11-12',
                                'religion' => 'Katolik',
                                'education' => 'SMA',
                                'occupation' => 'Pelajar',
                                'marital_status' => 'Belum Kawin',
                                'email' => 'davin.manjuntak@rt03.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401030002',
                        'address' => 'Jl. Anggrek No. 6',
                        'issued_at' => $today->copy()->subYears(6),
                        'head' => [
                            'name' => 'Sulastri Wahyuni',
                            'nik' => '3174010302020002',
                            'gender' => 'female',
                            'birth_place' => 'Padang',
                            'birth_date' => '1982-09-25',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Akuntan',
                            'marital_status' => 'Kawin',
                            'email' => 'sulastri.wahyuni@rt03.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Sulastri Wahyuni',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'female',
                                'birth_place' => 'Padang',
                                'birth_date' => '1982-09-25',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Akuntan',
                                'marital_status' => 'Kawin',
                                'email' => 'sulastri.wahyuni@rt03.warga.test',
                            ],
                            [
                                'name' => 'Ahmad Ridwan',
                                'relationship' => 'Suami',
                                'gender' => 'male',
                                'birth_place' => 'Padang',
                                'birth_date' => '1980-02-14',
                                'religion' => 'Islam',
                                'education' => 'SMA',
                                'occupation' => 'Koki',
                                'marital_status' => 'Kawin',
                                'email' => 'ahmad.ridwan@rt03.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401030003',
                        'address' => 'Jl. Anggrek No. 9',
                        'issued_at' => $today->copy()->subYears(5),
                        'head' => [
                            'name' => 'Teguh Sapto',
                            'nik' => '3174010303030003',
                            'gender' => 'male',
                            'birth_place' => 'Yogyakarta',
                            'birth_date' => '1987-07-19',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Pengacara',
                            'marital_status' => 'Kawin',
                            'email' => 'teguh.sapto@rt03.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Teguh Sapto',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'male',
                                'birth_place' => 'Yogyakarta',
                                'birth_date' => '1987-07-19',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Pengacara',
                                'marital_status' => 'Kawin',
                                'email' => 'teguh.sapto@rt03.warga.test',
                            ],
                            [
                                'name' => 'Maya Sapto',
                                'relationship' => 'Istri',
                                'gender' => 'female',
                                'birth_place' => 'Yogyakarta',
                                'birth_date' => '1989-01-29',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Wiraswasta',
                                'marital_status' => 'Kawin',
                                'email' => 'maya.sapto@rt03.warga.test',
                            ],
                            [
                                'name' => 'Nayla Sapto',
                                'relationship' => 'Anak',
                                'gender' => 'female',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '2015-03-15',
                                'religion' => 'Islam',
                                'education' => 'SD',
                                'occupation' => 'Pelajar',
                                'marital_status' => 'Belum Kawin',
                                'email' => 'nayla.sapto@rt03.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401030004',
                        'address' => 'Jl. Anggrek No. 12',
                        'issued_at' => $today->copy()->subYears(3),
                        'head' => [
                            'name' => 'Putri Larasati',
                            'nik' => '3174010304040004',
                            'gender' => 'female',
                            'birth_place' => 'Bandung',
                            'birth_date' => '1993-04-04',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Ilustrator',
                            'marital_status' => 'Kawin',
                            'email' => 'putri.larasati@rt03.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Putri Larasati',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'female',
                                'birth_place' => 'Bandung',
                                'birth_date' => '1993-04-04',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Ilustrator',
                                'marital_status' => 'Kawin',
                                'email' => 'putri.larasati@rt03.warga.test',
                            ],
                            [
                                'name' => 'Fajar Wibowo',
                                'relationship' => 'Suami',
                                'gender' => 'male',
                                'birth_place' => 'Bandung',
                                'birth_date' => '1992-10-26',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Fotografer',
                                'marital_status' => 'Kawin',
                                'email' => 'fajar.wibowo@rt03.warga.test',
                            ],
                        ],
                    ],
                    [
                        'family_card_number' => '317401030005',
                        'address' => 'Jl. Anggrek No. 15',
                        'issued_at' => $today->copy()->subYears(2),
                        'head' => [
                            'name' => 'Rahmawati Aziz',
                            'nik' => '3174010305050005',
                            'gender' => 'female',
                            'birth_place' => 'Makassar',
                            'birth_date' => '1994-06-21',
                            'religion' => 'Islam',
                            'education' => 'S1',
                            'occupation' => 'Peneliti',
                            'marital_status' => 'Kawin',
                            'email' => 'rahmawati.aziz@rt03.warga.test',
                        ],
                        'members' => [
                            [
                                'name' => 'Rahmawati Aziz',
                                'relationship' => 'Kepala Keluarga',
                                'gender' => 'female',
                                'birth_place' => 'Makassar',
                                'birth_date' => '1994-06-21',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Peneliti',
                                'marital_status' => 'Kawin',
                                'email' => 'rahmawati.aziz@rt03.warga.test',
                            ],
                            [
                                'name' => 'Ilham Saputra',
                                'relationship' => 'Suami',
                                'gender' => 'male',
                                'birth_place' => 'Makassar',
                                'birth_date' => '1992-12-01',
                                'religion' => 'Islam',
                                'education' => 'S1',
                                'occupation' => 'Analis Sistem',
                                'marital_status' => 'Kawin',
                                'email' => 'ilham.saputra@rt03.warga.test',
                            ],
                            [
                                'name' => 'Alya Saputra',
                                'relationship' => 'Anak',
                                'gender' => 'female',
                                'birth_place' => 'Jakarta',
                                'birth_date' => '2021-05-19',
                                'religion' => 'Islam',
                                'education' => 'BALITA',
                                'occupation' => 'Balita',
                                'marital_status' => 'Belum Kawin',
                                'email' => 'alya.saputra@rt03.warga.test',
                            ],
                        ],
                    ],
                ],
            ],
        ];

        foreach ($rtDefinitions as $rtDef) {
            $rt = Rt::create([
                'number' => $rtDef['number'],
                'name' => $rtDef['name'],
                'leader_name' => null,
                'email' => $rtDef['email'],
            ]);

            $leaderResident = null;

            foreach ($rtDef['households'] as $householdDef) {
                $household = Household::create([
                    'rt_id' => $rt->id,
                    'family_card_number' => $householdDef['family_card_number'],
                    'head_name' => $householdDef['head']['name'],
                    'head_nik' => $householdDef['head']['nik'],
                    'head_gender' => $householdDef['head']['gender'],
                    'head_birth_place' => $householdDef['head']['birth_place'],
                    'head_birth_date' => $householdDef['head']['birth_date'],
                    'head_religion' => $householdDef['head']['religion'],
                    'head_education' => $householdDef['head']['education'],
                    'head_occupation' => $householdDef['head']['occupation'],
                    'head_marital_status' => $householdDef['head']['marital_status'],
                    'head_nationality' => 'WNI',
                    'head_status' => Resident::STATUS_ACTIVE,
                    'head_email' => $householdDef['head']['email'],
                    'address' => $householdDef['address'],
                    'issued_at' => $householdDef['issued_at'],
                ]);

                foreach ($householdDef['members'] as $member) {
                    $resident = Resident::create([
                        'household_id' => $household->id,
                        'nik' => $member['nik'] ?? null,
                        'name' => $member['name'],
                        'relationship' => $member['relationship'],
                        'gender' => $member['gender'],
                        'birth_place' => $member['birth_place'],
                        'birth_date' => $member['birth_date'],
                        'religion' => $member['religion'],
                        'education' => $member['education'],
                        'occupation' => $member['occupation'],
                        'marital_status' => $member['marital_status'],
                        'email' => $member['email'] ?? null,
                        'nationality' => 'WNI',
                        'status' => Resident::STATUS_ACTIVE,
                        'status_effective_at' => $today->copy()->subYears(1),
                        'notes' => null,
                    ]);

                    if (($member['email'] ?? null) === $rtDef['leader_email']) {
                        $leaderResident = $resident;
                    }
                }

                $this->ensureHouseholdUser($household);
            }

            if ($leaderResident) {
                RtOfficial::create([
                    'rt_id' => $rt->id,
                    'resident_id' => $leaderResident->id,
                    'position' => 'Ketua RT',
                    'started_at' => $rtDef['leader_started_at'],
                    'ended_at' => null,
                    'notes' => null,
                ]);
            }
        }
    }

    private function ensureHouseholdUser(Household $household): void
    {
        User::updateOrCreate(
            ['email' => $household->family_card_number],
            [
                'name' => $household->head_name,
                'password' => bcrypt(config('app.default_resident_password', 'password123')),
                'role' => 'warga',
                'rt_id' => $household->rt_id,
                'household_id' => $household->id,
                'is_admin' => false,
                'is_active' => true,
            ]
        );
    }
}
